// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2;

/************************************************************/
/**
 * 
 */
public class Cliente Corporativo extends Cliente {
	/**
				 * 
				 */
				public Tarjeta Crédito
	tarjeta crédito;
	/**
	 * 
	 */
	public Vendedor vendedor;

	/**
	 * 
	 * @param nom 
	 */
	public void obtenirNom(String nom) {
	}
};
