// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2;

/************************************************************/
/**
 * 
 */
public class Línea Pedido
{
	/**
	 * 
	 */
	public Producto[] producto;
	/**
	 * 
	 */
	public Pedido pedido;

	/**
	 * 
	 */
	public void obtenirlinies() {
	}
};
