// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2;

/************************************************************/
/**
 * 
 */
public class Pedido {
	/**
				 * 
				 */
				public Línea Pedido[]
	línea pedido;
	/**
	 * 
	 */
	public Cliente cliente;

	/**
	 * 
	 */
	public void enviarPedido() {
	}
};
