// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2;

/************************************************************/
/**
 * 
 */
public class Producto {
	/**
	 * 
	 */
	public undefined Preu;
	/**
				 * 
				 */
				public Línea Pedido
	línea pedido;
};
