// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2;

/************************************************************/
/**
 * 
 */
public class Tarjeta Crédito extends
Sistema de Pago
{
	/**
	 * 
	 */
	public int[] LíneaCredito;
	/**
				 * 
				 */
				public Cliente Corporativo
	cliente corporativo;

	/**
	 * 
	 * @param LíneaCredito 
	 */
	static void setLíneaCredito(int LíneaCredito) {
	}

	/**
	 * 
	 */
	public void getLíneaCredito() {
	}
};
