// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2;

/************************************************************/
/**
 * 
 */
public class Vendedor {
	/**
				 * 
				 */
				public Cliente Corporativo[]
	cliente corporativo;

	/**
	 * 
	 * @param productes 
	 */
	public void obtenirProductes(unlimitednatural productes) {
	}
};
